### PR TITLE
add support for pandas Series to functions

### PR DESCRIPTION
**Pull request by briancappello**
After the discussion in https://github.com/mrjbq7/ta-lib/issues/120, I figured I'd put this together. It modifies `generate.py` and `generate_stream.py` to wrap the generated functions using the following pattern:

``` python
# maintain BC for the public interface; generated __doc__ goes here
def EMA( real, timeperiod=30 ):
    """ EMA(real[, timeperiod=?])

    Exponential Moving Average (Overlap Studies)

    Inputs:
        real: (np.ndarray or pd.Series)
    Parameters:
        timeperiod: 30
    Outputs:
        real
    """
    return _EMA(
        # all the input arrays get converted to np.ndarray if necessary
        real.values if isinstance(real, pd.Series) else real,
        # other arguments are passed along unchanged
        timeperiod
    )

# the actual implementation remains unchanged
@wraparound(False)  # turn off relative indexing from end of lists
@boundscheck(False) # turn off bounds-checking for entire function
def _EMA( np.ndarray real not None , int timeperiod=30 ):
    # ...
```

What do you think?

### CODE REVIEW

**Comment by mrjbq7** [comment]
Neat idea, but it should work even if ``pandas`` is not available on the system for import (similar to how ``talib.abstract`` does it).  Also, maybe we can make ``_EMA`` a ``cdef`` or something so its hidden and an implementation detail?

**Comment by briancappello** [comment]
OK, made ``pandas`` optional. I also had to move the ``not None`` check to the ``def`` declarations; ``cdef``s don't allow it, apparently: http://cython.readthedocs.io/en/latest/src/userguide/extension_types.html#extension-types-and-none

**Comment by briancappello** [comment]
Squashed my commits.

**Comment by mrjbq7** [comment]
Another option might be to do a sort of decorator approach (albeit maybe its a little slower because of the ``new_args`` packing):

```python
try:
    import pandas as pd
    def supportpandas(f):
        def _wrapper(*args, **kwds):
            new_args = [arg.values if isinstance(arg, pd.Series) else arg for arg in args]
            return f(*new_args, **kwds)
        return _wrapper
    for func_name in __TA_FUNCTION_NAMES__:
        func_object = globals()[func_name]
        globals()[func_name] = supportpandas(func_object)
except ImportError:
    pass
```

**Pull request closed without merging**
