### PR TITLE
Fix the build issue on Windows 8.1. The ta-lib-0.4.0-msvc.zip is unzi…

### PR DESCRIPTION
**Pull request by ForrestFeng**
…ped to C:\ta-lib correctly and I have VS2015 installsed

Recreate steps:
----------------------------------------
1. Install python with Miniconda3-latest-Windows-x86.exe
2. Run "conda insatll numpy" to install numpy package
3. Run "python setup.py install" to install talib

got the following error:
-----------------------------------------
$ python setup.py install
running install
running build
running build_py
running build_ext
building 'talib.stream' extension
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Miniconda3
\lib\site-packages\numpy\core\include -Ic:\ta-lib\c\include -IC:\Miniconda3\include -IC:\Miniconda3\include "-IC:\Pro
gram Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\A
TLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\ucrt" "-IC:\Program Files (x86)\Windows
 Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\shared" "-IC:\Program
 Files (x86)\Windows Kits\10\include\10.0.10586.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\
winrt" /Tctalib/stream.c /Fobuild\temp.win32-3.5\Release\talib/stream.obj
stream.c
c:\miniconda3\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated
 NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
talib/stream.c(276): fatal error C1083: Cannot open include file: 'ta-lib/ta_defs.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2

Fix
---------------------------------------------
The folder of c:\ta-lib\c\include is in the hearder file search path. And the  ta_defs.h header is there.
The error is that the  #include "ta-lib/ta_defs.h" had redundent path of ta-lib/. After removing it the build error is away.

### CODE REVIEW

**Comment by ForrestFeng** [comment]
This commit may not fix the build issue on Windows permanently.  There should be a better way to fix the header file cannot be found issue.

**Comment by mrjbq7** [comment]
Thanks for discovering this, although the way I'm handling cross-platform is with this fix instead (e89076914c8ef69744cc381ba742d9c38c0ab109).  It's been hard to keep these in because cython keeps the includes for the platform I build on, and I'm not sure how to tell it to keep the windows includes also without manually adding them back (and sometimes forgetting).

**Comment by femtotrader** [comment]
This kind of issue could be catched using CI https://github.com/mrjbq7/ta-lib/issues/104
(especially using AppVeyor)

**Comment by bigtan** [comment]
@mrjbq7 https://github.com/mrjbq7/ta-lib/pull/124 maybe a better solution, please review.

**Pull request closed without merging**
