### PR TITLE
Create ubuntu-install.sh

### PR DESCRIPTION
**Pull request by K-Kit**
simple shell script to make ubuntu install easier

### CODE REVIEW

**Comment by mrjbq7** [comment]
Most of those commands shouldn’t require `sudo`?

**Comment by mrjbq7** [comment]
This script isn't quite right exactly as is, but I like the idea of having these for different platforms as a guide/assist.

For example, aside from the ``sudo`` stuff, why does it add ``/usr/local/lib`` to the ``ld.conf`` when it tries to install with a ``--prefix=/usr``?

**Comment by mrjbq7** [comment]
Also, I would probably put this in the ``tools`` subdirectory.

And why does it need ``wheel`` and ``regex`` python  modules installed?  Those are not dependencies of ``TA-Lib``?

**Comment by K-Kit** [comment]
you're right sorry I copied it from the install script for a program i'm working on forgot to remove those parts

**Pull request merged**
